### ISSUE TITLE
USER STORY: View Paginated Property Lists

### ISSUE THREAD

**Issue by RadleighSmith** [RadleighSmith/apex-estates#1]
As a **User** I can **see a paginated list of properties for sale** so that **I can select which one I would like to look at.**

### Acceptance Criteria:
- AC 1: When accessing the platform the user should see a paginated list of properties available for sale given there is more than one property in the database.
- AC 2: Each page should display a defined number of properties (e.g., 10 properties per page).
- AC 3: Pagination controls (e.g., next page, previous page) should be present for easy navigation.

### Tasks:
- [ ] Develop the functionality to fetch and display properties in a paginated format.
- [ ] Implement a maximum number of properties per page before creating a new one.
- [ ] Create functional pagination controls, including next page and previous page buttons.
