### ISSUE TITLE
USER STORY: User Registration 

### ISSUE THREAD

**Issue by RadleighSmith** [RadleighSmith/apex-estates#2]
As a **New User** I can **Register an Account** so that **Login to the site**

### Acceptance Criteria:
- AC 1: User should only be able to register if not logged in.
- AC 2: The Registration form should include fields such as username, name, email, and password.
- AC 3: The Username and Email should be unique.
- AC 4: Only an Email can be inputted into the email field.

### Tasks:
- [ ] Import and configure Django User Authentication to manage user registration
- [ ] Implement validation for the email field to ensure that only valid email addresses are accepted.
- [ ] Extend the registration form to include fields for username, name, and password.
- [ ] Implement validation checks for mandatory fields.
- [ ] Display appropriate error messages if duplicate email or usernames are detected.
